name: Build PDF
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          pull: "NO-PULL"

      - name: Run script
        run: chmod u+x ./scripts/compile-latex.sh && ./scripts/compile-latex.sh
        shell: bash

      - uses: EndBug/add-and-commit@v7
        with:
          message: build - the latest pdf's of all LaTex files
          pull: 'NO-PULL'
